behave in pre-commit checks

diff --git a/tests/hooks/pre-commit b/tests/hooks/pre-commit
--- a/tests/hooks/pre-commit
+++ b/tests/hooks/pre-commit
@@ -1,7 +1,14 @@
 #!/bin/sh
-echo "Running tests before commit..."
+echo "Running unit tests before commit..."
 if ! make test; then
   echo "Tests failed. Commit aborted."
   exit 1
 fi
+
+echo "Running behave tests before commit..."
+if ! make test_bb; then
+  echo "Tests failed. Commit aborted."
+  exit 1
+fi
+
 
